# -*- coding: utf-8 -*-
"""mymath.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5LL_OEEKUNJE6yB34IqxFkEgODQ2Ck2
"""

from math import pi

def area_of_rectangle(width, height):
  return width*height

def circle_circumference(radius):
  return 2*pi*radius