# -*- coding: utf-8 -*-
"""mymodule.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qntkkJbLu7EjfgOF0b3tAGNDUiJurRc1
"""

def print_name(name):
  print("Your name is :", name)